name: Build
on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - run: |
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
      - uses: actions/checkout@master
        # with:
        #   path: ./src/github.com/${{ github.repository }}
      - run: CGO_ENABLED=0 go build
      - run: go test
  # lint:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: 'hairyhenderson/gomplate-ci-build:latest'
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         path: ./src/github.com/${{ github.repository }}
  #     - run: make lint
