name: Build
on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/gomplate-ci-build:latest
    steps:
      - run: |
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
      - uses: actions/checkout@v2.3.5
      - run: CGO_ENABLED=0 go build
      - run: go test
  lint:
    runs-on: ubuntu-latest
    container:
      image: 'hairyhenderson/gomplate-ci-build:latest'
    steps:
      - uses: actions/checkout@v2.3.5
      - run: make ci-lint
