name: Docker Build
on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Make Docker images
      run: docker build .
      env:
        DOCKER_BUILDKIT: '1'
