name: Docker Build
on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/gomplate-ci-build:latest
    steps:
    - uses: actions/checkout@v3
    - name: Make Docker images
      run: docker build .
      env:
        DOCKER_BUILDKIT: '1'
